version: "3.9"

services:
  # --- OpenTelemetry Collector ---
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.133.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./collector-minimal.yaml:/etc/otelcol-contrib/config.yaml:ro
      - ./demo_app.log:/var/tmp/demo_app.log:rw
    ports:
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "9464:9464"     # Prometheus exporter
    restart: unless-stopped

  # --- Prometheus ---
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    restart: unless-stopped

  # --- Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped

  # --- Loki ---
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped

  # --- Jaeger ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # UI
      # - "4317:4317"     # OTLP gRPC
      # - "4318:4318"     # OTLP HTTP
    restart: unless-stopped
    command: ["--memory.max-traces=50000"]

  # --- Demo App (Python) ---
  demo-app:
    build: ./demo-app
    container_name: demo-app
    volumes:
      - ./demo_app.log:/var/tmp/demo_app.log:rw
    depends_on:
      - otel-collector
    restart: unless-stopped
